### PR TITLE
storybook

### PR DESCRIPTION
**Pull request by fgottesmann**
Installation of storybook dependencies and .ignore files.
Check "Add storybook commit for more information"

### CODE REVIEW

**Review by saschahaselhuhn — APPROVED** [review]
gj, bro

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Review by RonjaMeinecke — APPROVED** [review]
GJ🚀

**Review by cboenke — APPROVED** [review]
LGTM 🚀

**Review by m-wiemers — APPROVED** [review]
I would have expected a css with 4000 lines. But so it is also possible 🚀

**Pull request merged**
